quarkus.application.name=barksquare-api

# OpenAPI metadata
mp.openapi.extensions.smallrye.info.title=BarkSquare API
mp.openapi.extensions.smallrye.info.version=0.1.0-SNAPSHOT
mp.openapi.extensions.smallrye.info.description=Social networking for pets. Like LinkedIn, but for your dog.

# Always serve Swagger UI, even in prod builds
quarkus.swagger-ui.always-include=true
