### List all Pets
GET http://localhost:8080/pets

### Get Pet
GET http://localhost:8080/pets/buiscuit

### Create Pet
POST http://localhost:8080/pets
Content-Type: application/json

{
  "name": "Rufus",
  "ownerHandle": "@tomr",
  "species": "DOG",
  "bio": "Bark twice if you love snacks. 🐾 Professional belly-rub consultant."
}

### Get All Squeaks
GET http://localhost:8080/squeaks

### Get All Dog Squeaks
GET http://localhost:8080/squeaks?species=DOG

### Post a Squak
POST http://localhost:8080/squeaks
X-Pet-Id: mr-fluffington
Content-Type: application/json

{
    "content": "Just chased my tail for 10 minutes. Caught it. Still don’t trust it."
}

### Get Biscuits Squeaks
GET http://localhost:8080/squeaks/my
Cookie: pet_session=biscuit